Document: ohrwurm
Title: Debian ohrwurm Manual
Author: <insert document author here>
Abstract: This manual describes what ohrwurm is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ohrwurm/ohrwurm.sgml.gz

Format: postscript
Files: /usr/share/doc/ohrwurm/ohrwurm.ps.gz

Format: text
Files: /usr/share/doc/ohrwurm/ohrwurm.text.gz

Format: HTML
Index: /usr/share/doc/ohrwurm/html/index.html
Files: /usr/share/doc/ohrwurm/html/*.html
